### ISSUE TITLE
Enable Atomify results in high CPU usage

### ISSUE THREAD

**Issue by remonlam** [jaebradley/atomify#17]
Love the plugin but when I'm enable the plugin it generates a huge CPU load.
The processes that cause this are **launchserviced** and **loginwindow**

When I disable the plugin I don't see any CPU spikes.

OSX 10.11.6

**Comment by jaebradley** [comment]
@remonlam thanks for pointing this out - I've been seeing this too and it's definitely concerning me. Will be investigating this more thoroughly in the coming days.

**Comment by jaebradley** [comment]
Hmmm...it might be tied to the DOM manipulation that I do when updating the state.

**Comment by noaht8um** [comment]
The exact same thing happened to me along with the "Dock" process spiking too. I liked it for the two minutes I was able to use it ;) I'd be willing to be a guinea pig once you find a fix for this :)

**Comment by remonlam** [comment]
@jaebradley No problem, hope it can be fixed, I really like this plugin!
@noaht8um Well it keeps working for me but my mbp makes a lot of noise because of cooling ;-)

**Comment by Newcratie** [comment]
Me too :)  launchservicesd	45%

**Comment by jaebradley** [comment]
@remonlam @noaht8um @Newcratie ok, so I'm not saying this issue is entirely fixed (or even close). However, the `0.3.0` release ( #21 ) has some logic that should reduce the number of times HTML gets updated / re-rendered and I've seen my `launchservicesd` CPU% "drop" to ~15%-20%. Not saying it's perfect, but it is a reduction I'm seeing on my end that hopefully also translates to a more usable plugin for you all as well.

**Comment by red-green** [comment]
I've noticed a constant 20% CPU used by "Atom Helper" whenever the Atom window is visible on the screen. Could it have something to do with the marquee animation that's happening all the time?
